# Generated by Django 5.2.3 on 2025-06-26 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0005_remove_task_assigned_to_task_assigned_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
