# Generated by Django 5.2.10 on 2026-01-26 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0012_alter_comment_options_attendance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="system_check_in",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
