# Generated by Django 5.2.10 on 2026-02-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0013_alter_attendance_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
