# Generated by Django 5.2.10 on 2026-02-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0014_customuser_designation_customuser_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="designation",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="phone",
        ),
        migrations.AddField(
            model_name="task",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="task_files/"),
        ),
    ]
