# Generated by Django 5.2.10 on 2026-02-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0015_remove_customuser_designation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="attachment",
        ),
    ]
