# Generated by Django 5.2.10 on 2026-02-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0016_remove_task_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="task_files/"),
        ),
    ]
