# Generated by Django 5.2.10 on 2026-03-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0019_chatmessage_delete_globalmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="pause_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="total_pause_seconds",
            field=models.IntegerField(default=0),
        ),
    ]
