# Generated by Django 5.2.10 on 2026-03-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0020_attendance_pause_start_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="pause_start",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="total_pause_seconds",
        ),
    ]
