# Generated by Django 5.2.10 on 2026-03-09 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0021_remove_attendance_pause_start_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Break",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("break_start", models.DateTimeField()),
                ("break_end", models.DateTimeField(blank=True, null=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="ToDoApp.attendance",
                    ),
                ),
            ],
        ),
    ]
