# Generated by Django 5.2.10 on 2026-03-28 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0022_break"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("cursor_x", models.IntegerField(blank=True, null=True)),
                ("cursor_y", models.IntegerField(blank=True, null=True)),
                (
                    "active_window",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("move", "Mouse Move"),
                            ("click", "Click"),
                            ("idle", "Idle"),
                            ("active", "Active"),
                        ],
                        default="move",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
