# Generated by Django 5.2.10 on 2026-03-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0024_apptimesession_dailyactivitysummary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeactivity",
            name="cursor_x",
        ),
        migrations.RemoveField(
            model_name="employeeactivity",
            name="cursor_y",
        ),
        migrations.AddField(
            model_name="employeeactivity",
            name="seconds",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="employeeactivity",
            name="event_type",
            field=models.CharField(
                choices=[("idle", "Idle"), ("active", "Active")],
                default="active",
                max_length=20,
            ),
        ),
    ]
