# Generated by Django 5.2.10 on 2026-03-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0025_remove_employeeactivity_cursor_x_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeeactivity",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AddField(
            model_name="employeeactivity",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeactivity",
            name="window_title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="employeeactivity",
            name="seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="employeeactivity",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
