# Generated by Django 5.2.10 on 2026-04-02 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0026_alter_employeeactivity_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrowserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=2000)),
                ("domain", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("timestamp", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("seconds", models.PositiveIntegerField(default=0)),
                ("activity_type", models.CharField(default="browser", max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="browser_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
